<?php

return [
    'brands' => [
        'Audi',
        'BMW',
        'Volkswagen',
        'Lada',
        'Toyota',
        'Skoda',
        'Nissan',
    ],
    'models' => [
        'A4',
        'A6',
        'A8',
        'W220',
        'Polo',
        'Tiguan',
        'Tuareg',
        'Jetta',
        'Golf',
        'Passat',
        'Granta',
        'Kalina',
        'Priora',
        'Rapid',
        'Fabia',
        '2107',
        '2110',
        'Almera',
        'Teana',
        'Pathfinder',
        'Patrol',
    ],
    'owner_names' => [
        'Alex',
        'Pavel',
        'Konstantin',
        'Ivan',
        'Mary',
        'Victory',
        'Ksenija',
        'Dmitry',
        'Andrew',
        'Nicolay',
        'Elena',
        'Svetlana'
    ],
    'owner_surnames' => [
        'Ivanov',
        'Petrov',
        'Naumov',
        'Stepanov',
        'Nikitin',
        'Samsomov',
        'Kozlov',
        'Morozov',
        'Kuznetsov',
        'Nosov',
    ],
    'regions' => [
        'Rostov',
        'Moscow',
        'Saint-Petersburg',
        'Novosibirsk',
        'Krasnodar',
        'Saratov',
        'Volgograd',
        'Kaliningrad',
        'Stavropol',
        'Irkutsk',
        'Vladivostok',
    ],
    'transmissions' => [
        'Manual',
        'Automatic',
        'Robot',
        'DSG',
    ]
];